### ISSUE TITLE
Rollout.io hot patching support for all methods

### ISSUE THREAD

**Issue by ekeren** [rollout/rollout.io-ios#1]
including:
- Private pods
- Apple's frameworks
- Third party libraries 
- Properties

**Comment by imoldman** [comment]
+1

**Comment by QuynhNguyen** [comment]
+1

**Comment by josejulio** [comment]
+1

**Comment by AdminPlayDay** [comment]
+1

**Comment by ekeren** [comment]
version 0.8.6+ supports:
-  Private pods 
-  Third party libraries (when they debug symbols included in it).
-  Properties

**Comment by ekeren** [comment]
The current version (1.2.0) include a "Custom hot-patch" link right above the search function search box. This allows you to create a hot patch based on class name, method name and a signature
