### ISSUE TITLE
Configuration script failed

### ISSUE THREAD

**Issue by hkalexling** [rollout/rollout.io-ios#104]
Hi,

I would like to try rollout so I made a blank iOS app called `RolloutTest` and followed the instructions on your site to install Rollout.io via CocoaPods. Everything works fine until I run the configuration script with `Pods/Rollout.io/install/configure_pod.sh -k 580068f2f570e6b138ccbd6f`. Here's what I got in the terminal:

> Pods/Rollout.io/install/configure_pod.sh -k 580068f2f570e6b138ccbd6f
Configuring project "/Users/alex_ling/Desktop/RolloutTest/Pods/Rollout.io/../../RolloutTest.xcodeproj"
2016-10-14 15:59:46.501 Installer[51583:20289194] *** Terminating app due to uncaught exception '(null)', reason: 'Project file not found at file path /Users/alex_ling/Desktop/RolloutTest/Pods/Rollout.io/../../RolloutTest.xcodeproj.rollouttemp.xcodeproj'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fffcdc1252b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fffe22dacad objc_exception_throw + 48
	2   CoreFoundation                      0x00007fffcdc90a0d +[NSException raise:format:] + 205
	3   Installer                           0x00000001000168a2 -[XCProject initWithFilePath:] + 259
	4   Installer                           0x000000010000b2f0 -[Installer initWithParameters:] + 170
	5   Installer                           0x00000001000028db -[RolloutInstaller installWithParameters:] + 166
	6   Installer                           0x0000000100002825 -[RolloutInstaller installCocoaPods:] + 100
	7   Installer                           0x0000000100001e47 main + 1133
	8   Installer                           0x0000000100001804 start + 52
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Pods/Rollout.io/install/configure_pod.sh: line 93: 51583 Abort trap: 6           "$BIN_DIR"/Installer "$xcode_dir" "$app_key"

and here's my Podfile:

```
use_frameworks!
platform :ios, '8.0'

target 'RolloutTest' do

pod 'Rollout.io', '~> 1.4.0'

end
```

So what's the problem here? Thanks

**Comment by silyevsk** [comment]
Hi Alex,

I'm sorry for the late response. Can you please run the following command (it's the installer in verbose mode) and send us the output?

> Pods/Rollout.io/install/Installer -d /Users/alex_ling/Desktop/RolloutTest/Pods/Rollout.io/../../RolloutTest.xcodeproj 580068f2f570e6b138ccbd6f

**Comment by hkalexling** [comment]
Thanks for the reply and here's the output :)

> Pods/Rollout.io/install/Installer -d /Users/alex_ling/Desktop/RolloutTest/Pods/Rollout.io/../../RolloutTest.xcodeproj 580068f2f570e6b138ccbd6f
Installing cocoa pods
new xcodeproj configuration 7
new xcodeproj configuration 7
Rollout install path /Users/alex_ling/Desktop/RolloutTest/Pods/Rollout.io/../../RolloutTest.xcodeproj.rollouttemp.xcodeproj key 580068f2f570e6b138ccbd6f
prev xcodeproj configuration found 0
Rollout uninstall path /Users/alex_ling/Desktop/RolloutTest/Pods/Rollout.io/../../RolloutTest.xcodeproj.rollouttemp.xcodeproj key 580068f2f570e6b138ccbd6f
all groups: (
    "Group: displayName = Frameworks, key=1E8A4C63651A59AEE2EA4ADB",
    "Group: displayName = Pods, key=4048B3E02D2F308CE82CE0D9",
    "Group: displayName = LaunchScreen.storyboard, key=7116D7AE1DB0C78C005F8669",
    "Group: displayName = Supporting Files, key=7116D7A01DB0C78C005F8669",
    "Group: displayName = Products, key=7116D79E1DB0C78C005F8669",
    "Group: displayName = (null), key=7116D7941DB0C78B005F8669",
    "Group: displayName = RolloutTest, key=7116D79F1DB0C78C005F8669",
    "Group: displayName = Main.storyboard, key=7116D7A91DB0C78C005F8669"
)
uninstall group Rollout
group Rollout not found in project
uninstall group Frameworks
uninstall script Rollout.io dsym upload
uninstall script Rollout.io post-build
uninstall script Rollout.io pre-build
uninstall script Rollout Code analyzer
uninstall build setting LDPLUSPLUS linker/clang++
uninstall build setting SWIFT_EXEC
uninstall build setting LIPO lipo/lipo
uninstall build setting LD linker/clang
uninstall build setting CC compiler/clang
uninstall search path Rollout-ios-SDK/Rollout
Saved project
The IDEFoundation framework failed to load: Error Domain=NSCocoaErrorDomain Code=3587 "dlopen_preflight(/Applications/Xcode-beta.app/Contents/Frameworks/IDEFoundation.framework/IDEFoundation): Library not loaded: @rpath/DVTAnalytics.framework/Versions/A/DVTAnalytics
  Referenced from: /Applications/Xcode-beta.app/Contents/Frameworks/IDEFoundation.framework/IDEFoundation
  Reason: image not found" UserInfo={NSLocalizedFailureReason=The bundle is damaged or missing necessary resources., NSLocalizedRecoverySuggestion=Try reinstalling the bundle., NSFilePath=/Applications/Xcode-beta.app/Contents/Frameworks/IDEFoundation.framework/IDEFoundation, NSDebugDescription=dlopen_preflight(/Applications/Xcode-beta.app/Contents/Frameworks/IDEFoundation.framework/IDEFoundation): Library not loaded: @rpath/DVTAnalytics.framework/Versions/A/DVTAnalytics
  Referenced from: /Applications/Xcode-beta.app/Contents/Frameworks/IDEFoundation.framework/IDEFoundation
  Reason: image not found, NSBundlePath=/Applications/Xcode-beta.app/Contents/Frameworks/IDEFoundation.framework, NSLocalizedDescription=The bundle “IDEFoundation” couldn’t be loaded because it is damaged or missing necessary resources.}

> error while converting file to plist. The IDEFoundation framework failed to load: Error Domain=NSCocoaErrorDomain Code=3587 "dlopen_preflight(/Applications/Xcode-beta.app/Contents/Frameworks/IDEFoundation.framework/IDEFoundation): Library not loaded: @rpath/DVTAnalytics.framework/Versions/A/DVTAnalytics
  Referenced from: /Applications/Xcode-beta.app/Contents/Frameworks/IDEFoundation.framework/IDEFoundation
  Reason: image not found" UserInfo={NSLocalizedFailureReason=The bundle is damaged or missing necessary resources., NSLocalizedRecoverySuggestion=Try reinstalling the bundle., NSFilePath=/Applications/Xcode-beta.app/Contents/Frameworks/IDEFoundation.framework/IDEFoundation, NSDebugDescription=dlopen_preflight(/Applications/Xcode-beta.app/Contents/Frameworks/IDEFoundation.framework/IDEFoundation): Library not loaded: @rpath/DVTAnalytics.framework/Versions/A/DVTAnalytics
  Referenced from: /Applications/Xcode-beta.app/Contents/Frameworks/IDEFoundation.framework/IDEFoundation
  Reason: image not found, NSBundlePath=/Applications/Xcode-beta.app/Contents/Frameworks/IDEFoundation.framework, NSLocalizedDescription=The bundle “IDEFoundation” couldn’t be loaded because it is damaged or missing necessary resources.}

> all groups: (
    "Group: displayName = Frameworks, key=1E8A4C63651A59AEE2EA4ADB",
    "Group: displayName = Pods, key=4048B3E02D2F308CE82CE0D9",
    "Group: displayName = LaunchScreen.storyboard, key=7116D7AE1DB0C78C005F8669",
    "Group: displayName = Supporting Files, key=7116D7A01DB0C78C005F8669",
    "Group: displayName = Products, key=7116D79E1DB0C78C005F8669",
    "Group: displayName = (null), key=7116D7941DB0C78B005F8669",
    "Group: displayName = RolloutTest, key=7116D79F1DB0C78C005F8669",
    "Group: displayName = Main.storyboard, key=7116D7A91DB0C78C005F8669"
)
2016-10-15 20:19:17.151 Installer[93789:23208001] *** Terminating app due to uncaught exception '(null)', reason: 'Project file not found at file path /Users/alex_ling/Desktop/RolloutTest/Pods/Rollout.io/../../RolloutTest.xcodeproj.rollouttemp.xcodeproj'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fffcdc1252b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fffe22dacad objc_exception_throw + 48
	2   CoreFoundation                      0x00007fffcdc90a0d +[NSException raise:format:] + 205
	3   Installer                           0x00000001000168a2 -[XCProject initWithFilePath:] + 259
	4   Installer                           0x000000010000b2f0 -[Installer initWithParameters:] + 170
	5   Installer                           0x00000001000028db -[RolloutInstaller installWithParameters:] + 166
	6   Installer                           0x0000000100002825 -[RolloutInstaller installCocoaPods:] + 100
	7   Installer                           0x0000000100001e47 main + 1133
	8   Installer                           0x0000000100001804 start + 52
)
libc++abi.dylib: terminating with uncaught exception of type NSException
[1]    93789 abort      Pods/Rollout.io/install/Installer -d  580068f2f570e6b138ccbd6f

**Comment by silyevsk** [comment]
Thanks for the info. I'm not sure yet what happens, looks like a temp proj folder is not created, but unfortunately we don't have enough info printed by the installer. Can you please also run the following and attach the output:

> a=/Users/alex_ling/Desktop/RolloutTest/Pods/Rollout.io/../../RolloutTest.xcodeproj.rollouttemp.xcodeproj
> ls -ld $a
> mkdir $a
> ls -ld $a
> ls -ld $(dirname $a)

**Comment by hkalexling** [comment]
Sure.

> drwxr-xr-x  5 alex_ling  staff  170 Oct 15 20:19 /Users/alex_ling/Desktop/RolloutTest/Pods/Rollout.io/../../RolloutTest.xcodeproj.rollouttemp.xcodeproj
mkdir: /Users/alex_ling/Desktop/RolloutTest/Pods/Rollout.io/../../RolloutTest.xcodeproj.rollouttemp.xcodeproj: File exists
drwxr-xr-x  5 alex_ling  staff  170 Oct 15 20:19 /Users/alex_ling/Desktop/RolloutTest/Pods/Rollout.io/../../RolloutTest.xcodeproj.rollouttemp.xcodeproj
drwxr-xr-x  11 alex_ling  staff  374 Oct 15 20:19 /Users/alex_ling/Desktop/RolloutTest/Pods/Rollout.io/../..

**Comment by silyevsk** [comment]
Since it's a test project, can you zip it (as it is, with the temp project folder) and either attach here, or send to me at sergey@rollout.io ?

**Comment by silyevsk** [comment]
I've found the root cause thanks to the zip you've sent: the project file contains some unicode character added by CocoaPods which confuses our installer. We provided a fix for this issue a while ago but looks like it wasn't sufficient. Which CocoaPods version do you have (pod --version)? I hope that we will fix version in the next update, but in the meanwhile, to start using/trying Rollout I suggest any of the following workarounds:

1. Create a new test project and try Rollout with the installer app rather than with CocoaPods (i.e. don't run CocoaPods on the project at all)
2. Switch to another CocoaPods version (1.0.1 doesn't add this character to the proj file)
3. Manually rename the cocoapods build phases in the project (there are three of them)

**Comment by hkalexling** [comment]
Yeah I am using CocoaPods 1.0.0. I switched to the installer and it works fine. Thanks for the help :)
