### ISSUE TITLE
persistent tweaks

### ISSUE THREAD

**Issue by ekeren** [rollout/rollout.io-ios#13]
The ability to save tweaks for the next time the application is started so it will work even if there is no network and if sync should be called

**Comment by Armenm** [comment]
+1

**Comment by josejulio** [comment]
+1

**Comment by purpleblues** [comment]
+1

**Comment by SteveYurka** [comment]
+1

**Comment by silyevsk** [comment]
This was implemented in 0.9, closing the issue
