### ISSUE TITLE
Linker error when compiling for armv7

### ISSUE THREAD

**Issue by coverback** [rollout/rollout.io-ios#16]
Hi,

When trying to run the app in debug mode with the latest Rollout.io coming from the cocoapods (0.6.2), there is a linker error saying this:

    ld: don't know how to convert branch instruction ef408714
    referencing _objc_storeStrong.island to bx in
    '-[RolloutDynamic initWithInvocationsListFactory:rolloutErrors:]'
    from /Users/name/Library/Developer/Xcode/DerivedData/app-fquimvxtkghwoleojzyyutkgarin/Build/Intermediates/app.build/Debug-iphoneos/app.build/Objects-normal/armv7/RolloutDynamic.o
    for architecture armv7

Device is iPhone 5c, and while naturally it uses armv7s, we don't compile for it, so it's falling back to armv7.

**Comment by coverback** [comment]
Can be caused by #11. Removing the workaround fixes this. Closing.

**Comment by rlopezdiez** [comment]
If you remove the workaround, you will have long compilation times again. Any way to fix this issue (which we are also having) without removing the workaround?

**Comment by ekeren** [comment]
This issue is no longer relevant, solved as part as  #11
