### ISSUE TITLE
Rollout.io hot patching support replacement for arguments in before action

### ISSUE THREAD

**Issue by imoldman** [rollout/rollout.io-ios#2]
sometimes, we found the crash is caught by some unusual argument, like `nil`, `@""`, etc.

In before action, we can replace it to a safe param.

**Comment by josejulio** [comment]
+1

**Comment by ekeren** [comment]
supported on 0.8.6+
![screen shot 2015-06-30 at 10 14 32 am](https://cloud.githubusercontent.com/assets/1727147/8425673/dc94816a-1f10-11e5-895d-4d871bdb5ac8.png)
