### ISSUE TITLE
RolloutSwizzlerDynamic.include Read-only variable is not assignable

### ISSUE THREAD

**Issue by basvankuijck** [rollout/rollout.io-ios#20]
Line 8201:
```*$p = swizzleBlock();```

**Comment by ekeren** [comment]
Hi @basvankuijck, sorry for that.
I'll contact you directly via mail to get more info on this.

**Comment by ekeren** [comment]
Root cause found (thanks to @basvankuijck `RolloutSwizzlerDynamic.include`)
The problem happens when the original function returns `"const float"` and Rollout.io autogenerated code does not compile.

**Comment by ekeren** [comment]
@silyevsk lets make sure we add tests for  `const CGFloat` and `const void *`

**Comment by basvankuijck** [comment]
Okay, thanks for looking into it.
I resolved the issue by changing `const CGFloat` return values to `CGFloat` ones. Was no particular reason I needed it to be constant.
Now I can build the project without any issues

**Comment by ekeren** [comment]
Issue resolved as part of SDK 0.7.1 (http://support.rollout.io/v1.0/docs/change-log#071)
