### ISSUE TITLE
Add 'OR statement' to tweak condition

### ISSUE THREAD

**Issue by ekeren** [rollout/rollout.io-ios#25]
Currently conditions only support the AND statements
![screen shot 2015-02-21 at 2 30 51 pm](https://cloud.githubusercontent.com/assets/1727147/6314081/4ca3bef8-b9d6-11e4-9735-08a5f7d2ddb7.png)

**Comment by josejulio** [comment]
+1

**Comment by ekeren** [comment]
This is available via JavaScript on SDK version 0.14.1
