### ISSUE TITLE
Custom attributes for analytics events

### ISSUE THREAD

**Issue by josejulio** [rollout/rollout.io-ios#27]
Currently when you submit a mixpanel event (unsure about google) it appears as "mp_event", you should ideally be able to select to which tracking you would like to submit the data and according to that, show  an event name input and maybe a json (or a list of param : value elements) to send as additional data.

**Comment by ekeren** [comment]
+1

**Comment by ekeren** [comment]
Till this issue is fixed you can use JavaScript (SDK 0.14.1) for this issue
