### ISSUE TITLE
Call a different method from a hot patch

### ISSUE THREAD

**Issue by ekeren** [rollout/rollout.io-ios#42]
As a user I would like to be hot patch a method and
- Call a different method instead of the original method
- Call a different method from a catch block
- Call a different method after original method was executed
- Call a different method before original method was executed 
- call a different method using the argument supplied to original method

**Comment by ehlersd** [comment]
+1

**Comment by intari** [comment]
+1

**Comment by dwaynewilliams** [comment]
+1

**Comment by ekeren** [comment]
This is now available via [ObjcBox#call](http://support.rollout.io/docs/javascript-docs#objcboxcall) method 
on SDK version 0.14.1

**Comment by bimawa** [comment]
Whooohoo! THX! A LOT!
