### ISSUE TITLE
Add support for condition based on an object property path

### ISSUE THREAD

**Issue by ekeren** [rollout/rollout.io-ios#5]
An example for the usage:

A method, which has a single param, NSURLRequest. 
When request.url is empty string(not nil), application crash 

Rollout should allow user to disabled the invocation if "the $0.URL.absoluteString.length isNill"

**Comment by imoldman** [comment]
+1

**Comment by ekeren** [comment]
This is now available via [ObjcBox#call](http://support.rollout.io/docs/javascript-docs#objcboxcall) method
