### ISSUE TITLE
Bitcode on Xcode 7？

### ISSUE THREAD

**Issue by sbhhbs** [rollout/rollout.io-ios#50]
Will this framework support Bitcode in the coming Xcode?

**Comment by silyevsk** [comment]
There are several levels of bitcode support:
* Hot-patching on devices with architectures for which the app was compiled - this works fine, bitcode doesn't prevent Rollout from working on these archs
* Not causing issues on architectures for which the app was compiled with bitcode (and not directly with Xcode): this means the SDK should be disabled on such devices - this is not the case now, I hope we will set it relatively soon
* Support hot-patching on architectures for which the app was not compiled with Xcode, but via bitcode - this is probably not going to be implemented soon

Could you please tell us what usages of bitcode you have in mind?

**Comment by JacobSyndeo** [comment]
Well, targets with bitcode enabled that reference your framework won't build. It's an issue I'm hitting as well.
<img width="799" alt="screen shot 2015-11-09 at 12 03 36 pm" src="https://cloud.githubusercontent.com/assets/1004637/11043555/8581674e-86da-11e5-9cc1-c77d1371c9f8.png">

**Comment by silyevsk** [comment]
We've fixed this in 0.11 which will be released in a few days.

**Comment by silyevsk** [comment]
0.11 released, closing this
