### ISSUE TITLE
Stop using dynamic code

### ISSUE THREAD

**Issue by silyevsk** [rollout/rollout.io-ios#53]
Currently, Rollout generates "dynamic code" during the Rollout build phase. This code is required for hot-patching methods. This can sometimes create complications integrating Rollout in projects and also increases build time and final app binary size.
We need to switch to fully dynamic methods execution, without generating this helper code.
**This is currently in development**

**Comment by YogevSitton** [comment]
+1

**Comment by eytanbiala** [comment]
+1

**Comment by QuynhNguyen** [comment]
+1

**Comment by mrezk** [comment]
+1

**Comment by natanrolnik** [comment]
+1

**Comment by OlegAnghelov** [comment]
+1

**Comment by DevAndArtist** [comment]
+1

**Comment by sbhhbs** [comment]
+1

**Comment by coverback** [comment]
@ekeren What are the drawbacks on moving the files into `.gitignore`? They files are not persistent and local checkout and `pod install` causes them to be re-generated anyway.
It is very irritating that every `pod install` even with same pod versions causes changes in virtually all Rollout files.

**Comment by ekeren** [comment]
SDK version 0.14.1 is not using dynamic code any more!!!

**Comment by eytanbiala** [comment]
Awesome!
