### ISSUE TITLE
Rollout.io 0.9.2 build error

### ISSUE THREAD

**Issue by muyexi** [rollout/rollout.io-ios#58]
I used to use Rollout.io 0.8.7 with Cocopods, today I try to update to 0.9.2, 
then I came across a lot errors when building:

> /PROJECT-PATH/Rollout-ios-SDK/auto_generated_code/RolloutDynamic_01.m:25:41: 'RolloutDynamic' does not have a member named '_configuration'

> /PROJECT-PATH/Rollout-ios-SDK/auto_generated_code/RolloutDynamic_01.m:26:54: 'RolloutDynamic' does not have a member named '_invocationsListFactory'

> /PROJECT-PATH/Rollout-ios-SDK/auto_generated_code/RolloutDynamic_01.m:27:31: Receiver type 'RolloutInvocationsList' for instance message is a forward declaration

> /PROJECT-PATH/Rollout-ios-SDK/auto_generated_code/RolloutDynamic_01.m:33:12: Property 'forceMainThreadType' not found on object of type 'RolloutInvocation *'

> /PROJECT-PATH/Rollout-ios-SDK/auto_generated_code/RolloutDynamic_01.m:33:35: Use of undeclared identifier 'RolloutInvocation_ForceMainThreadType_off'

> /PROJECT-PATH/Rollout-ios-SDK/auto_generated_code/RolloutDynamic_01.m:35:14: No visible @interface for 'RolloutInvocation' declares the selector 'runBefore'

> /PROJECT-PATH/Rollout-ios-SDK/auto_generated_code/RolloutDynamic_01.m:37:13: Property 'originalArguments' not found on object of type 'RolloutInvocation *'

> /PROJECT-PATH/Rollout-ios-SDK/auto_generated_code/RolloutDynamic_01.m:38:34: Property 'tweakedArguments' not found on object of type 'RolloutInvocation *'

> /PROJECT-PATH/Rollout-ios-SDK/auto_generated_code/RolloutDynamic_01.m:40:22: No visible @interface for 'RolloutInvocation' declares the selector 'type'

> /PROJECT-PATH/Rollout-ios-SDK/auto_generated_code/RolloutDynamic_01.m:65:14: No visible @interface for 'RolloutInvocation' declares the selector 'runBefore'

> /PROJECT-PATH/Rollout-ios-SDK/auto_generated_code/RolloutDynamic_01.m:67:13: Property 'originalArguments' not found on object of type 'RolloutInvocation *'

> /PROJECT-PATH/Rollout-ios-SDK/auto_generated_code/RolloutDynamic_01.m:68:34: Property 'tweakedArguments' not found on object of type 'RolloutInvocation *'

> /PROJECT-PATH/Rollout-ios-SDK/auto_generated_code/RolloutDynamic_01.m:70:22: No visible @interface for 'RolloutInvocation' declares the selector 'type'

> /PROJECT-PATH/Rollout-ios-SDK/auto_generated_code/RolloutDynamic_01.m:93:16: Property 'forceMainThreadType' not found on object of type 'RolloutInvocation *'

> /PROJECT-PATH/Rollout-ios-SDK/auto_generated_code/RolloutDynamic_01.m:133:41: 'RolloutDynamic' does not have a member named '_configuration'

> /PROJECT-PATH/Rollout-ios-SDK/auto_generated_code/RolloutDynamic_01.m:134:54: 'RolloutDynamic' does not have a member named '_invocationsListFactory'

> /PROJECT-PATH/Rollout-ios-SDK/auto_generated_code/RolloutDynamic_01.m:135:31: Receiver type 'RolloutInvocationsList' for instance message is a forward declaration

> /PROJECT-PATH/Rollout-ios-SDK/auto_generated_code/RolloutDynamic_01.m:141:12: Property 'forceMainThreadType' not found on object of type 'RolloutInvocation *'

> /PROJECT-PATH/Rollout-ios-SDK/auto_generated_code/RolloutDynamic_01.m:141:35: Use of undeclared identifier 'RolloutInvocation_ForceMainThreadType_off'

> Too many errors emitted, stopping now

**Comment by ekeren** [comment]
can you try running:
```
 Pods/Rollout.io/lib/tweaker -c
```

**Comment by muyexi** [comment]
Below is the output, and it's OK now, thanks.
> Cleaning the cache dir, and emptying the dynamic files

**Comment by ekeren** [comment]
ok, cleaning the cache should happen automatically when upgrading rollout.io verison.
We'll add this fix to the next release of the SDK (0.10) , thanks for reporting it.
