### ISSUE TITLE
Add common misused api hot patch template

### ISSUE THREAD

**Issue by sbhhbs** [rollout/rollout.io-ios#59]
For example, able to hot fix 'NSString containsString' which only exist after iOS 8 are often misused and crash on iOS 7.

**Comment by ekeren** [comment]
+1 - great Idea, we also think this is a very useful solution 

We have just release polyfills (on 0.10.0) - see use case http://support.rollout.io/docs/use-case-missing-method-on-older-ios-version

It is not the complete solution you are looking for, but it is a step in the right direction... I'll update this ticket more when we have progress

**Comment by ekeren** [comment]
This issue is resolved with the power of polyfils with JavaScript, together they allow you to create a new method in the system
