### ISSUE TITLE
Do not warn on third-part libs in dsym

### ISSUE THREAD

**Issue by silyevsk** [rollout/rollout.io-ios#61]
Some libs (apptimize, google sign-in) have debug symbols unstripped, but accessing them with dsymutil results in warnings, which then appear in the build.

We should find a way to suppress this kind of dsymutil warnings, or prevent the final warnings in some other way.

**Comment by purpleblues** [comment]
+1

**Comment by ekeren** [comment]
@silyevsk - is this resolved in 0.10.2 ?

**Comment by silyevsk** [comment]
Yes, closing it

**Comment by silyevsk** [comment]
Actually, the ticket is about warnings, we still have warnings in some cases (https://github.com/rollout/rollout.io-ios/issues/64)

**Comment by silyevsk** [comment]
We've decided to remove the warnings by redirecting all the dsymutil output to /dev/null - until now we only got false positives with such output, so it's probably better to stop alerting on this.

The fix will will be released with Rollout SDK 0.11, until then it's available as a patch: https://gist.github.com/silyevsk/1b92d72e3f51b6e85bb6   . To apply the patch, please run the following from the Rollout directory under your project (either Pods/Rollout.io/ if Rollout was installed via CocoaPods, or Rollous-ios-SDK/ if installed with Rollout installer):

`patch -p1 < "<path to the patch>"`
