### ISSUE TITLE
Alternative action: Trigger custom function instead of the alert box.

### ISSUE THREAD

**Issue by DevAndArtist** [rollout/rollout.io-ios#62]
I'd wish that we could trigger a custom `void` function instead of the alert box action. If the function supports a `dictionary` input, it would be nice to pass a `dictionary of strings` right from the dashboard. This way it would be possible for the app developer to present a custom alert to the enduser and also match the UI.

**Comment by ekeren** [comment]
@DevAndArtist you can now (almost) achieve it by using custom analytics action. Check out http://support.rollout.io/v1.0/docs/faq#what-happens-when-i-add-analytics-events-via-rollo it shows you how you can get NSDictionary from analytics action and actually do what ever you want (orignally for sending custom analytics provider) 


@silyevsk @omeryo - this is an interesting angle I always wanted rollout to go to

**Comment by ekeren** [comment]
+1

**Comment by dwaynewilliams** [comment]
+1

**Comment by ekeren** [comment]
This can be achieved with JavaScript as of SDK (0.14.1) you can call any method you want using  [ObjcBox#call](http://support.rollout.io/docs/javascript-docs#objcboxcall) method 

No need to even prepare the action in advance
