### ISSUE TITLE
Build errors with duplicated methods in generated files

### ISSUE THREAD

**Issue by bfcatch** [rollout/rollout.io-ios#73]
There are a bunch of duplicated methods generated in RolloutDynamic_xx.m files

It started happening on some of our computers yesterday.
And that seems to be caused by the different or problematic json file pulled down in tweaker_functions.json.gz, as I tried replacing the .cache folder with the one that's working, and then did `pod install` and the issue didn't happen.

Also i want to note that our project uses cocoapods, and has multiple targets with different api keys, not sure if this is related to this issue.

**Comment by silyevsk** [comment]
Please try to run `Pods/Rollout.io/lib/tweaker -c`
It will clean the cache and remove all the dynamic code. Then during the build the dynamic code will be recreated.

**Comment by bfcatch** [comment]
thanks @silyevsk for the tip

Sorry, forgot to follow this up until this issue happens again now.
seems like clearing the cache only hides the problem
One of our computers constantly has this problem, so we have to clear the cache from time to time...

Anyone knows the root cause to it please?

Thanks

**Comment by silyevsk** [comment]
Actually, I recommend upgrading to 0.14.4 - it doesn't have the dynamic code at all, nor the cache, so the issue won't reoccur with this version.

**Comment by ekeren** [comment]
This issue is already solved in version 0.14.4
