### ISSUE TITLE
access/modify ivars from javascript

### ISSUE THREAD

**Issue by ekeren** [rollout/rollout.io-ios#76]
Right now only properties are accessible through javascript API, we would like to also add ability to get and set ivars

**Comment by anuj-rajput** [comment]
+1

**Comment by juliensechaud** [comment]
+1

could be very useful !

**Comment by jerelevine** [comment]
+1

**Comment by ekeren** [comment]
Given a class instance defined using:

	@interface MyObject {
		NSString *_string;	
		NSInteger _anInteger;
	}
	@end
	
it is possible to access and modify the ivars in patches like so:

	// get the value from the ivar
	var theInteger = self.call('valueForKey:', '_anInteger').jsNumber();
	
	// modify it in your patch
	theInteger += 100;
	
	// set the value back
	self.call('setValue:forKey:', R.createNSNumber(theInteger), '_anInteger');
	
notice we have to create an NSNumber and send that as the value, `-setValue:forKey:` does the right thing and converts it to an NSInteger, as explained in the [documentation](http://developer.apple.com/library/ios/#DOCUMENTATION/Cocoa/Conceptual/KeyValueCoding/Articles/DataTypes.html) for the method: 

> The default implementations of `valueForKey:` and `setValue:forKey:` provide support for automatic object wrapping of the non-object data types, both scalars and structs.

> Once `valueForKey:` has determined the specific accessor method or instance variable that is used to supply the value for the specified key, it examines the return type or the data type. If the value to be returned is not an object, an `NSNumber` or `NSValue` object is created for that value and returned in its place.

> Similarly, setValue:forKey: determines the data type required by the appropriate accessor or instance variable for the specified key. If the data type is not an object, then the value is extracted from the passed object using the appropriate `-<type>Value` method.

**Comment by anuj-rajput** [comment]
Awesome @ekeren! Is it live already? Can't wait to try it out

**Comment by ekeren** [comment]
@anuj-rajput sure it is live and kicking (see [docs](http://support.rollout.io/docs/javascript-examples#get-and-set-ivar))
