### ISSUE TITLE
configure_pod.sh / installer should not change project.pbproj file format

### ISSUE THREAD

**Issue by silyevsk** [rollout/rollout.io-ios#78]
We use quite an old xcodeproj package, which changes project.pbroj file format to xml. A new xcodeproj doesn't do it (https://github.com/CocoaPods/Xcodeproj/blob/master/CHANGELOG.md#0220-2015-02-25)

**Workaround**:
Until we upgrade xcodeproj, the xcproj tool (https://github.com/0xced/xcproj) can be used - xcodeproj calls it after the modification and fixes the format.

**Comment by holysin** [comment]
It works, thanks for the solution.

**Comment by ekeren** [comment]
This issue is already resolved in current SDK version
