### ISSUE TITLE
Enable user management section under setting

### ISSUE THREAD

**Issue by ekeren** [rollout/rollout.io-ios#8]

**Comment by ekeren** [comment]
this issue is resolved as part of 0.8.1 (http://support.rollout.io/v1.0/docs/change-log#081)

**Comment by xdnm** [comment]
hi  dear rollout team
	I can open your home page (rollout.io),but I can not see anything in it except a blue background.
	Is there anything wrong with your homepage?

	thanks for your kindly help.

**Comment by ekeren** [comment]
Hey @xdnm - what browser are you using?
