### ISSUE TITLE
Error loading functions.

### ISSUE THREAD

**Issue by VincentSit** [rollout/rollout.io-ios#81]
I just signed up for rollout, and integrated SDK. But when I entered my App, it display "Error loading functions. Let us check why." Does that have a relationship with me live in China?

I tried to connect to the VPN before launch app, but this error still occurs.

**Comment by ekeren** [comment]
Your application method are extracted from the dsym file that gets uploaded to rollout servers from your build script (when you build/run your project from Xcode)

Can you setup VPN and build your project again?

**Comment by VincentSit** [comment]
Thank you for your reply, let me try.

**Comment by VincentSit** [comment]
The problem has been resolved. Thank you.

I think it because I stopped my app before the uploading finished.
