### ISSUE TITLE
Add .super property (or method) to JS patching

### ISSUE THREAD

**Issue by ekeren** [rollout/rollout.io-ios#84]
Need to add the ability to get the super out of [ObjcBox](http://support.rollout.io/docs/javascript-docs#objcbox)

**Comment by luko-g** [comment]
+1

**Comment by juliensechaud** [comment]
+1

**Comment by jerelevine** [comment]
+1

**Comment by zaitsevyan** [comment]
+1

**Comment by galoz** [comment]
+1

**Comment by dnd0513** [comment]
+1

**Comment by ekeren** [comment]
callSuper method was added to SDK 1.7.0 see [docs](http://support.rollout.io/docs/javascript-docs#objcboxcallsuper)

**Comment by Shimi** [comment]
Fixed in SDK 1.7.0
http://support.rollout.io/docs/change-log#section-sdk-1-7-0
