### ISSUE TITLE
get property of a class in its category is always 'undefined'

### ISSUE THREAD

**Issue by xn1108100154** [rollout/rollout.io-ios#89]
Hi, 
I have a property named `xxx` in class `AClass`, then I wanna replace implementation of a method named `-(void)aMethod` in `AClass+Category`. I use `self.xxx` in `- aMethod`, but it is always undefined.

**Comment by silyevsk** [comment]
Hi,

Please use `self.call('xxx')` to access the property - there's no direct properties access, and the call function is used to call methods on self.

**Comment by xn1108100154** [comment]
Haha, that's it. Thank you very much for solving my online bug. You may need add more in docs.：)
