### ISSUE TITLE
Force a function to run from main thread (sync) 

### ISSUE THREAD

**Issue by ekeren** [rollout/rollout.io-ios#9]
Add the ability to force a function to run from Main Thread.

**Comment by Armenm** [comment]
+1

**Comment by ekeren** [comment]
Available in SDK version 0.7 
See change log http://support.rollout.io/v1.0/docs/change-log#070
and example use case http://support.rollout.io/v1.0/docs/use-case-datareload-method-of-a-table-view-is-call
