### ISSUE TITLE
Add support for JS patches on iOS 7

### ISSUE THREAD

**Issue by silyevsk** [rollout/rollout.io-ios#90]
Currently, JS patches are ignored on iOS 7. We need to test and enable JS on iOS 7 if there are no issues.

**Comment by esam091** [comment]
What are the issues exactly? Not being able to use JS patch on iOS 7 is pretty much a deal breaker to us. 😕

**Comment by silyevsk** [comment]
@esam091 - I don't know if there are issues. We will post a comment here when we have an update (we need to test it). In the current version of SDK it's disabled however.

**Comment by ekeren** [comment]
There are a bunch of memory leaks, our test don't pass when running on ios7 version. 

@esam091  - why is this a deal breaker for you guys?

**Comment by esam091** [comment]
Nevermind, we finally dropped our support for iOS 7 🙂

**Comment by ekeren** [comment]
We will not add this feature, ios7 and javascript are not working together and ios7 is getting older (almost like this ticket)
